[package]
name = "pingorahub-release-worker"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
pingorahub-application = { path = "../../crates/application" }
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true

